import { WorkflowNode, WorkflowConnection, ZapierExport, MakeExport, N8nExport } from "@shared/schema";

export const generateZapierJSON = (nodes: WorkflowNode[], connections: WorkflowConnection[]): ZapierExport => {
  const triggerNode = nodes.find(node => node.type === 'trigger');
  const actionNodes = nodes.filter(node => node.type === 'action');

  return {
    trigger: {
      app: triggerNode?.app || 'webhook',
      event: triggerNode?.action || 'unknown_trigger',
    },
    actions: actionNodes.map(node => ({
      app: node.app,
      action: node.action.toLowerCase().replace(/\s+/g, '_'),
    })),
  };
};

export const generateMakeJSON = (nodes: WorkflowNode[], connections: WorkflowConnection[]): MakeExport => {
  return {
    scenario: {
      name: `Workflow - ${nodes[0]?.action || 'Automation'}`,
      modules: nodes.map(node => ({
        service: node.app.replace('-', ''),
        operation: node.action.toLowerCase().replace(/\s+/g, '-'),
      })),
    },
  };
};

export const generateN8nJSON = (nodes: WorkflowNode[], connections: WorkflowConnection[]): N8nExport => {
  const n8nConnections: Record<string, any> = {};
  
  // Build connections object
  connections.forEach(conn => {
    if (!n8nConnections[conn.source]) {
      n8nConnections[conn.source] = { main: [[]] };
    }
    
    const targetNode = nodes.find(n => n.id === conn.target);
    if (targetNode) {
      n8nConnections[conn.source].main[0].push({
        node: conn.target,
        type: 'main',
        index: 0,
      });
    }
  });

  return {
    nodes: nodes.map(node => ({
      type: `n8n-nodes-base.${node.app.replace('-', '')}`,
      name: node.action,
    })),
    connections: n8nConnections,
  };
};

// Helper function to generate a complete workflow export with metadata
export const generateWorkflowExport = (
  nodes: WorkflowNode[],
  connections: WorkflowConnection[],
  platform: 'zapier' | 'make' | 'n8n',
  metadata?: {
    name?: string;
    description?: string;
    tags?: string[];
  }
) => {
  const baseWorkflow = {
    zapier: () => generateZapierJSON(nodes, connections),
    make: () => generateMakeJSON(nodes, connections),
    n8n: () => generateN8nJSON(nodes, connections),
  }[platform]();

  return {
    ...baseWorkflow,
    metadata: {
      name: metadata?.name || `${platform} Workflow`,
      description: metadata?.description || 'Generated by WorkflowBridge',
      platform,
      createdAt: new Date().toISOString(),
      nodeCount: nodes.length,
      tags: metadata?.tags || [],
    },
  };
};

// Validation functions
export const validateWorkflow = (nodes: WorkflowNode[], connections: WorkflowConnection[]) => {
  const errors: string[] = [];
  
  // Check if there's at least one trigger
  const triggers = nodes.filter(n => n.type === 'trigger');
  if (triggers.length === 0) {
    errors.push('Workflow must have at least one trigger node');
  }
  
  // Check if there's at least one action
  const actions = nodes.filter(n => n.type === 'action');
  if (actions.length === 0) {
    errors.push('Workflow must have at least one action node');
  }
  
  // Check for disconnected nodes
  const connectedNodeIds = new Set([
    ...connections.map(c => c.source),
    ...connections.map(c => c.target),
  ]);
  
  const disconnectedNodes = nodes.filter(n => !connectedNodeIds.has(n.id));
  if (disconnectedNodes.length > 0) {
    errors.push(`Found ${disconnectedNodes.length} disconnected nodes`);
  }
  
  return {
    isValid: errors.length === 0,
    errors,
  };
};
